ARG NODE_VERSION
FROM node:$NODE_VERSION as uilayer

WORKDIR /app

COPY ./portal-ui/package.json ./
COPY ./portal-ui/yarn.lock ./
RUN yarn install

COPY ./portal-ui .

RUN yarn install && make build-static

USER node
