// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2021 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package admin_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/console/models"
)

// ListUsersWithBucketAccessOKCode is the HTTP code returned for type ListUsersWithBucketAccessOK
const ListUsersWithBucketAccessOKCode int = 200

/*ListUsersWithBucketAccessOK A successful response.

swagger:response listUsersWithBucketAccessOK
*/
type ListUsersWithBucketAccessOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewListUsersWithBucketAccessOK creates ListUsersWithBucketAccessOK with default headers values
func NewListUsersWithBucketAccessOK() *ListUsersWithBucketAccessOK {

	return &ListUsersWithBucketAccessOK{}
}

// WithPayload adds the payload to the list users with bucket access o k response
func (o *ListUsersWithBucketAccessOK) WithPayload(payload *models.User) *ListUsersWithBucketAccessOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users with bucket access o k response
func (o *ListUsersWithBucketAccessOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersWithBucketAccessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListUsersWithBucketAccessDefault Generic error response.

swagger:response listUsersWithBucketAccessDefault
*/
type ListUsersWithBucketAccessDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListUsersWithBucketAccessDefault creates ListUsersWithBucketAccessDefault with default headers values
func NewListUsersWithBucketAccessDefault(code int) *ListUsersWithBucketAccessDefault {
	if code <= 0 {
		code = 500
	}

	return &ListUsersWithBucketAccessDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list users with bucket access default response
func (o *ListUsersWithBucketAccessDefault) WithStatusCode(code int) *ListUsersWithBucketAccessDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list users with bucket access default response
func (o *ListUsersWithBucketAccessDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list users with bucket access default response
func (o *ListUsersWithBucketAccessDefault) WithPayload(payload *models.Error) *ListUsersWithBucketAccessDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list users with bucket access default response
func (o *ListUsersWithBucketAccessDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListUsersWithBucketAccessDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
