// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2022 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/console/models"
)

// GetAUserPolicyOKCode is the HTTP code returned for type GetAUserPolicyOK
const GetAUserPolicyOKCode int = 200

/*GetAUserPolicyOK A successful response.

swagger:response getAUserPolicyOK
*/
type GetAUserPolicyOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetAUserPolicyOK creates GetAUserPolicyOK with default headers values
func NewGetAUserPolicyOK() *GetAUserPolicyOK {

	return &GetAUserPolicyOK{}
}

// WithPayload adds the payload to the get a user policy o k response
func (o *GetAUserPolicyOK) WithPayload(payload string) *GetAUserPolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get a user policy o k response
func (o *GetAUserPolicyOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAUserPolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetAUserPolicyDefault Generic error response.

swagger:response getAUserPolicyDefault
*/
type GetAUserPolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAUserPolicyDefault creates GetAUserPolicyDefault with default headers values
func NewGetAUserPolicyDefault(code int) *GetAUserPolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAUserPolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get a user policy default response
func (o *GetAUserPolicyDefault) WithStatusCode(code int) *GetAUserPolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get a user policy default response
func (o *GetAUserPolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get a user policy default response
func (o *GetAUserPolicyDefault) WithPayload(payload *models.Error) *GetAUserPolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get a user policy default response
func (o *GetAUserPolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAUserPolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
