// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LoginOauth2CallbackHandlerFunc turns a function with the right signature into a login oauth2 callback handler
type LoginOauth2CallbackHandlerFunc func(LoginOauth2CallbackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LoginOauth2CallbackHandlerFunc) Handle(params LoginOauth2CallbackParams) middleware.Responder {
	return fn(params)
}

// LoginOauth2CallbackHandler interface for that can handle valid login oauth2 callback params
type LoginOauth2CallbackHandler interface {
	Handle(LoginOauth2CallbackParams) middleware.Responder
}

// NewLoginOauth2Callback creates a new http.Handler for the login oauth2 callback operation
func NewLoginOauth2Callback(ctx *middleware.Context, handler LoginOauth2CallbackHandler) *LoginOauth2Callback {
	return &LoginOauth2Callback{Context: ctx, Handler: handler}
}

/*LoginOauth2Callback swagger:route GET /login/oauth2/callback UserAPI loginOauth2Callback

Identity Provider oauth2 callback endpoint.

*/
type LoginOauth2Callback struct {
	Context *middleware.Context
	Handler LoginOauth2CallbackHandler
}

func (o *LoginOauth2Callback) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLoginOauth2CallbackParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
