// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2020 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package operator_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/console/models"
)

// OperatorListBucketsOKCode is the HTTP code returned for type OperatorListBucketsOK
const OperatorListBucketsOKCode int = 200

/*OperatorListBucketsOK A successful response.

swagger:response operatorListBucketsOK
*/
type OperatorListBucketsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListBucketsResponse `json:"body,omitempty"`
}

// NewOperatorListBucketsOK creates OperatorListBucketsOK with default headers values
func NewOperatorListBucketsOK() *OperatorListBucketsOK {

	return &OperatorListBucketsOK{}
}

// WithPayload adds the payload to the operator list buckets o k response
func (o *OperatorListBucketsOK) WithPayload(payload *models.ListBucketsResponse) *OperatorListBucketsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the operator list buckets o k response
func (o *OperatorListBucketsOK) SetPayload(payload *models.ListBucketsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OperatorListBucketsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*OperatorListBucketsDefault Generic error response.

swagger:response operatorListBucketsDefault
*/
type OperatorListBucketsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewOperatorListBucketsDefault creates OperatorListBucketsDefault with default headers values
func NewOperatorListBucketsDefault(code int) *OperatorListBucketsDefault {
	if code <= 0 {
		code = 500
	}

	return &OperatorListBucketsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the operator list buckets default response
func (o *OperatorListBucketsDefault) WithStatusCode(code int) *OperatorListBucketsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the operator list buckets default response
func (o *OperatorListBucketsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the operator list buckets default response
func (o *OperatorListBucketsDefault) WithPayload(payload *models.Error) *OperatorListBucketsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the operator list buckets default response
func (o *OperatorListBucketsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *OperatorListBucketsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
