// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2021 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package operator_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/console/models"
)

// ConfigureMonitoringCreatedCode is the HTTP code returned for type ConfigureMonitoringCreated
const ConfigureMonitoringCreatedCode int = 201

/*ConfigureMonitoringCreated A successful response.

swagger:response configureMonitoringCreated
*/
type ConfigureMonitoringCreated struct {
}

// NewConfigureMonitoringCreated creates ConfigureMonitoringCreated with default headers values
func NewConfigureMonitoringCreated() *ConfigureMonitoringCreated {

	return &ConfigureMonitoringCreated{}
}

// WriteResponse to the client
func (o *ConfigureMonitoringCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*ConfigureMonitoringDefault Generic error response.

swagger:response configureMonitoringDefault
*/
type ConfigureMonitoringDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewConfigureMonitoringDefault creates ConfigureMonitoringDefault with default headers values
func NewConfigureMonitoringDefault(code int) *ConfigureMonitoringDefault {
	if code <= 0 {
		code = 500
	}

	return &ConfigureMonitoringDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the configure monitoring default response
func (o *ConfigureMonitoringDefault) WithStatusCode(code int) *ConfigureMonitoringDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the configure monitoring default response
func (o *ConfigureMonitoringDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the configure monitoring default response
func (o *ConfigureMonitoringDefault) WithPayload(payload *models.Error) *ConfigureMonitoringDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the configure monitoring default response
func (o *ConfigureMonitoringDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConfigureMonitoringDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
