// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MultiBucketReplicationEdit multi bucket replication edit
//
// swagger:model multiBucketReplicationEdit
type MultiBucketReplicationEdit struct {

	// arn
	Arn string `json:"arn,omitempty"`

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// priority
	Priority int32 `json:"priority,omitempty"`

	// replicate delete markers
	ReplicateDeleteMarkers bool `json:"replicateDeleteMarkers,omitempty"`

	// replicate deletes
	ReplicateDeletes bool `json:"replicateDeletes,omitempty"`

	// replicate existing objects
	ReplicateExistingObjects bool `json:"replicateExistingObjects,omitempty"`

	// replicate metadata
	ReplicateMetadata bool `json:"replicateMetadata,omitempty"`

	// rule state
	RuleState bool `json:"ruleState,omitempty"`

	// storage class
	StorageClass string `json:"storageClass,omitempty"`

	// tags
	Tags string `json:"tags,omitempty"`
}

// Validate validates this multi bucket replication edit
func (m *MultiBucketReplicationEdit) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this multi bucket replication edit based on context it is used
func (m *MultiBucketReplicationEdit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MultiBucketReplicationEdit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MultiBucketReplicationEdit) UnmarshalBinary(b []byte) error {
	var res MultiBucketReplicationEdit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
