// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO Console Server
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReleaseMetrics release metrics
//
// swagger:model releaseMetrics
type ReleaseMetrics struct {

	// bug fixes
	BugFixes float64 `json:"bug_fixes,omitempty"`

	// changes
	Changes float64 `json:"changes,omitempty"`

	// new feature
	NewFeature float64 `json:"new_feature,omitempty"`

	// releases
	Releases float64 `json:"releases,omitempty"`

	// security
	Security float64 `json:"security,omitempty"`
}

// Validate validates this release metrics
func (m *ReleaseMetrics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this release metrics based on context it is used
func (m *ReleaseMetrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReleaseMetrics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReleaseMetrics) UnmarshalBinary(b []byte) error {
	var res ReleaseMetrics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
